# Setup
title:               DanubeRS
tagline:             'Monkey with a typewriter'
description:         ''
url:                 https://blog.danubers.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Daniel Park
  url:               https://twitter.com/DanubeDev
  email:             daniel+blog@danubers.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-93481484-1
