# Setup
title:               DanubeRS
tagline:             'Monkey with a typewriter'
description:         ''
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Daniel Park
  url:               https://twitter.com/DanubeDev
  email:             daniel+blog@danubers.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: UA-93481484-1

# Socials
social:
  twitter: 'https://twitter.com/DanubeDev'
  linkedin: 'https://www.linkedin.com/in/danubers'
